#define MESSAGE_LENGTH_DEF 1024

#define TIMEOUT_SERVER_PAWN 1000
#define TIMEOUT_SERVER_LOADER -1
#define TIMEOUT_SERVER_GUI 1000
#define TIMEOUT_LOADER_SERVER -1
#define TIMEOUT_LOADER_GUI -1

#define WORKER_THREADS_NR_DEF 10